### ISSUE TITLE
Short and vague Conclusion at the end

### ISSUE THREAD

**Issue by DaveAndersonCo** [diku-dk/MarketplaceOnOrleans#6]
Interesting project with good use case and details. 
I just can't understand the Conclusion section in the related document. https://arxiv.org/pdf/2403.12605

Everything is described in details, but the Conclusion is short and vague. The authors say nothing at all about what shortcomings prevented them from implementing it as they intended.
It would have been helpful if they gave some kind of feedback and indicated what additional feature they would like to have in MS Orleans to support this use case.

Regards,
Dave

**Comment by rnlaigner** [comment]
Thanks for the comment. Sections 7.3 and Section 7.4 contain what you are looking for. Conclusion section is constrained by page limits that conferences impose.
